import json
import streamlit as st

from compareAgent import (
    MODEL,
    build_initial_user_message,
    build_messages,
    create_client,
    get_json_reply,
    normalize_products,
)


def init_state():
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "ui_messages" not in st.session_state:
        st.session_state.ui_messages = []
    if "started" not in st.session_state:
        st.session_state.started = False
    if "completed" not in st.session_state:
        st.session_state.completed = False


def reset_chat():
    st.session_state.messages = []
    st.session_state.ui_messages = []
    st.session_state.started = False
    st.session_state.completed = False


def append_assistant_reply(data, model):
    status = data.get("status")
    st.session_state.messages.append({"role": "assistant", "content": json.dumps(data)})

    if status == "need_more_info":
        text = data.get("question", "Please provide more details.")
        st.session_state.ui_messages.append({"role": "assistant", "content": text, "model": model})
        return

    if status == "final_recommendation":
        text = data.get("recommendation", "No recommendation provided.")
        st.session_state.ui_messages.append({"role": "assistant", "content": text, "model": model})
        st.session_state.completed = True
        return

    st.session_state.ui_messages.append(
        {
            "role": "assistant",
            "content": "I returned an unexpected format and will retry automatically.",
            "model": model,
        }
    )
    st.session_state.messages.append(
        {
            "role": "user",
            "content": "Your JSON format was invalid. Return one of the two required schemas exactly.",
        }
    )


def run_assistant_turn(client, model):
    data = get_json_reply(client, st.session_state.messages, model=model)
    append_assistant_reply(data, model)

    if (
        not st.session_state.completed
        and st.session_state.ui_messages
        and "unexpected format" in st.session_state.ui_messages[-1]["content"]
    ):
        data = get_json_reply(client, st.session_state.messages, model=model)
        append_assistant_reply(data, model)


def main():
    st.set_page_config(page_title="Product Compare Agent", page_icon=":speech_balloon:")
    st.title("Product Compare Agent")
    st.caption("Chat interface for product recommendations with follow-up questions.")

    init_state()

    with st.sidebar:
        st.subheader("Settings")
        requestModel = st.selectbox("Model", MODEL)
        model = requestModel if requestModel in MODEL else "gpt-5-nano"
        api_key = st.text_input("API Key", value="", type="password")
        requires_user_key = model == "gpt-4.1-mini"
        missing_required_key = requires_user_key and not api_key.strip()

        if missing_required_key:
            st.caption("API key is required for gpt-4.1-mini")

        start_clicked = st.button("Start New Chat", disabled=missing_required_key)
        if start_clicked:
            if model not in MODEL:
                st.error("Invalid model selection.")
                st.stop()
            if model == "gpt-4.1-mini" and not api_key.strip():
                st.error("Please provide an API key for gpt-4.1-mini.")
                st.stop()
            reset_chat()
            st.rerun()

    for message in st.session_state.ui_messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if message["role"] == "assistant" and message.get("model"):
                st.caption(f"Generated by {message['model']}")

    try:
        client = create_client(
            api_key_override=api_key if api_key else None,
        )
    except Exception as error:
        st.error(f"Failed to initialize client: {error}")
        return

    if not st.session_state.started:
        prompt = st.chat_input("Enter products separated by commas (e.g. MacBook Air, Dell XPS 13)")
        if prompt:
            products = normalize_products(prompt)
            if not products:
                st.warning("Please enter at least one product name.")
                return

            st.session_state.started = True
            st.session_state.ui_messages.append({"role": "user", "content": prompt})
            initial_user_message = build_initial_user_message(products)
            st.session_state.messages = build_messages(initial_user_message)

            try:
                with st.spinner("Loading..."):
                    run_assistant_turn(client, model)
            except Exception as error:
                st.error(f"Could not get assistant reply: {error}")
                return
            st.rerun()
        return

    prompt = st.chat_input("Reply to the assistant")
    if prompt:
        if st.session_state.completed:
            st.info("Recommendation is complete. Start a new chat to compare other products.")
            return

        st.session_state.ui_messages.append({"role": "user", "content": prompt})
        st.session_state.messages.append({"role": "user", "content": prompt})
        try:
            with st.spinner("Loading..."):
                run_assistant_turn(client, model)
        except Exception as error:
            st.error(f"Could not get assistant reply: {error}")
            return
        st.rerun()


if __name__ == "__main__":
    main()
